server.port=8081

spring.application.name=api-gateway

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.cloud.gateway.routes[0].id=urbano-femn-api
spring.cloud.gateway.routes[0].uri=lb://UrbanoFemn
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].id=urbano-femn-openapi
spring.cloud.gateway.routes[1].uri=lb://UrbanoFemn
spring.cloud.gateway.routes[1].predicates[0]=Path=/v3/api-docs/**

spring.cloud.gateway.routes[2].id=urbano-femn-swagger
spring.cloud.gateway.routes[2].uri=lb://UrbanoFemn
spring.cloud.gateway.routes[2].predicates[0]=Path=/swagger-ui/**

spring.cloud.gateway.routes[3].id=urbano-femn-doc
spring.cloud.gateway.routes[3].uri=lb://UrbanoFemn
spring.cloud.gateway.routes[3].predicates[0]=Path=/doc/**

management.endpoints.web.exposure.include=health,info,gateway